initialisation of chrome options and change default value of  guzzle client option to false
athena-oss/plugin-php pull request #20
Opened 2017-01-25 04:39 UTC by suciolx

changes 
1. initialisation of chrome options
2. set default value of verify to false (guzzle client)

2017-01-25 13:09 UTC, pproenca requested changes

2017-01-25 13:09 UTC, pproenca commented on src/Api/ApiClientBuilder.php
> +        $guzzleClient->setDefaultOption('verify',false);
This option should be retrieved from the settings class and if it's empty, then default to `false`

2017-01-27 05:54 UTC, suciolx commented on src/Api/ApiClientBuilder.php
> +        $guzzleClient->setDefaultOption('verify',false);
what is setting class? is it Json file configuration?

2017-01-27 13:43 UTC, pproenca commented on src/Api/ApiClientBuilder.php
> +        $guzzleClient->setDefaultOption('verify',false);
You can add a method in the `ApiClientBuilder` that set's whether the verify option is true or false.

Then in the `Athena.php` file, where the `ApiClientBuilder` is called, you pass the pass the value to the builder using the settings class.

Example:

`https://github.com/athena-oss/plugin-php/blob/master/src/Athena.php#L278`

2017-01-27 16:57 UTC, suciolx commented
@pproenca Hi Pedro please check my new commit

2017-01-27 17:07 UTC, merged